# Generated by Django 5.0.6 on 2026-07-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-attendance_date'],
            },
        ),
        migrations.CreateModel(
            name='OffDay',
            fields=[
                ('off_day_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('off_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'off_days',
            },
        ),
    ]
