# Generated by Django 5.0.6 on 2026-07-07 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('observation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('observation_date', models.DateField()),
                ('setting_tag', models.CharField(choices=[('small_group', 'Small Group'), ('one_to_one', '1:1'), ('whole_class', 'Whole Class')], max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='studentapp.student')),
            ],
            options={
                'db_table': 'observations',
                'ordering': ['-observation_date'],
                'indexes': [models.Index(fields=['student', 'observation_date'], name='observation_student_d4795b_idx')],
            },
        ),
    ]
