# Generated by Django 5.0.6 on 2026-07-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorFeedback',
            fields=[
                ('behavior_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_date', models.DateField()),
                ('incident_classification', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('concern', 'Concern')], max_length=10)),
                ('engagement_rating', models.PositiveSmallIntegerField()),
                ('observation_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'behavior_feedback',
                'ordering': ['-event_date'],
            },
        ),
    ]
