# Generated by Django 5.0.6 on 2026-07-07 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('behaviorapp', '0001_initial'),
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorfeedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_feedback', to='studentapp.student'),
        ),
        migrations.AddIndex(
            model_name='behaviorfeedback',
            index=models.Index(fields=['student', 'event_date'], name='behavior_fe_student_6c6639_idx'),
        ),
        migrations.AddConstraint(
            model_name='behaviorfeedback',
            constraint=models.CheckConstraint(check=models.Q(('engagement_rating__gte', 1), ('engagement_rating__lte', 5)), name='chk_engagement_rating_1_5'),
        ),
    ]
