# Generated by Django 5.0.6 on 2026-07-10 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentapp', '0002_alter_student_student_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('recommendation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('current_strengths', models.TextField()),
                ('recommended_activities', models.TextField()),
                ('skill_gaps', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='studentapp.student')),
            ],
            options={
                'db_table': 'ai_recommendations',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['student', '-generated_at'], name='ai_recommen_student_2b86d1_idx')],
            },
        ),
    ]
