# Generated by Django 5.0.6 on 2026-07-07 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignmentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentFeedback',
            fields=[
                ('feedback_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ccss_code', models.CharField(blank=True, max_length=50, null=True)),
                ('assessment_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('graded', 'Graded'), ('reviewed', 'Reviewed')], default='graded', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_entries', to='assignmentapp.assignment')),
            ],
            options={
                'db_table': 'assignment_feedback',
                'ordering': ['-assessment_date'],
            },
        ),
    ]
