# Generated by Django 5.0.6 on 2026-07-07 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedbackapp', '0001_initial'),
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentfeedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_feedback', to='studentapp.student'),
        ),
        migrations.AddIndex(
            model_name='assignmentfeedback',
            index=models.Index(fields=['student', 'subject'], name='assignment__student_c15486_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentfeedback',
            index=models.Index(fields=['student', 'assessment_date'], name='assignment__student_aa755f_idx'),
        ),
    ]
