# Generated by Django 5.2.13 on 2026-07-09 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentapp', '0002_alter_student_student_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIParentMessage',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('classification', models.CharField(choices=[('progress_update', 'Progress Update'), ('concern', 'Concern'), ('achievement', 'Achievement')], max_length=20)),
                ('tone', models.CharField(choices=[('formal', 'Formal'), ('friendly', 'Friendly')], max_length=10)),
                ('parent_email', models.EmailField(max_length=150)),
                ('message_text', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], default='draft', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_messages', to='studentapp.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_parent_messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher', 'student'], name='ai_parent_m_teacher_82fe40_idx'), models.Index(fields=['sent_at'], name='ai_parent_m_sent_at_26aee0_idx')],
            },
        ),
    ]
