# Generated by Django 5.0.6 on 2026-07-07 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100)),
                ('classification', models.CharField(choices=[('advance', 'Advance'), ('on_track', 'On Track'), ('developing', 'Developing'), ('risk', 'Risk')], max_length=20)),
                ('tag', models.CharField(choices=[('above_grade_level', 'Above Grade Level'), ('at_grade_level', 'At Grade Level'), ('approaching_grade_level', 'Approaching Grade Level'), ('below_grade_level', 'Below Grade Level')], max_length=30)),
                ('avg_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('generated_by_ai', models.BooleanField(default=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups_tbl',
                'ordering': ['group_name'],
            },
        ),
        migrations.CreateModel(
            name='GroupGenerationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('classification', models.CharField(choices=[('advance', 'Advance'), ('on_track', 'On Track'), ('developing', 'Developing'), ('risk', 'Risk')], max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='groupapp.group')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_generation_history',
                'ordering': ['-generated_date'],
            },
        ),
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groupapp.group')),
            ],
            options={
                'db_table': 'group_students',
            },
        ),
    ]
