# Generated by Django 5.2.13 on 2026-07-09 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groupapp', '0002_initial'),
        ('studentapp', '0002_alter_student_student_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('intervention_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('individual_student', 'Individual Student'), ('individual_group', 'Individual Group')], max_length=20)),
                ('intervention_type', models.TextField()),
                ('reason', models.TextField()),
                ('start_date', models.DateField()),
                ('frequency', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='groupapp.group')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='studentapp.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interventions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher', 'target_type'], name='interventio_teacher_f807f9_idx'), models.Index(fields=['student'], name='interventio_student_0cbe5f_idx'), models.Index(fields=['group'], name='interventio_group_i_65c374_idx')],
                'constraints': [models.CheckConstraint(check=models.Q(models.Q(('group__isnull', True), ('student__isnull', False), ('target_type', 'individual_student')), models.Q(('group__isnull', False), ('student__isnull', True), ('target_type', 'individual_group')), _connector='OR'), name='chk_intervention_target_consistency')],
            },
        ),
    ]
