# Generated by Django 5.0.6 on 2026-07-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0.6)),
                ('max_tokens', models.IntegerField(default=4000)),
                ('ai_model', models.CharField(default='gpt-4o-mini', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_configurations',
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tokens_used', models.IntegerField(default=0)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('endpoint', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_usage_logs',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=250)),
                ('region_district_office', models.CharField(max_length=250)),
                ('registration_status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'schools',
                'ordering': ['school_name'],
            },
        ),
    ]
