# Generated by Django 5.0.6 on 2026-07-10 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('analytical_focus', models.CharField(max_length=255)),
                ('temporal_bounds', models.IntegerField()),
                ('report_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_reports', to='adminapp.school')),
            ],
            options={
                'db_table': 'analysis_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
