# Generated by Django 5.0.6 on 2026-07-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('subject', models.CharField(db_index=True, max_length=100)),
                ('target_type', models.CharField(choices=[('all_groups', 'All Groups'), ('individual_student', 'Individual Student'), ('individual_group', 'Individual Group')], max_length=25)),
                ('ai_difficulty', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10)),
                ('ccss_code', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('number_of_questions', models.PositiveIntegerField(default=5)),
                ('unique_assignment_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_generation_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assignments',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentMailLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('parent_email', models.EmailField(max_length=150)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assignment_mail_log',
            },
        ),
        migrations.CreateModel(
            name='AssignmentQuestion',
            fields=[
                ('question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'assignment_questions',
                'ordering': ['question_order'],
            },
        ),
    ]
