# Generated by Django 5.0.6 on 2026-07-10 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentapp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('submission_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=200)),
                ('roll_number', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('parent_name', models.CharField(max_length=200)),
                ('attachment', models.FileField(upload_to='assignment_submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignmentapp.assignment')),
            ],
            options={
                'db_table': 'assignment_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
