# Generated by Django 5.2.13 on 2026-07-09 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignmentapp', '0002_initial'),
        ('groupapp', '0002_initial'),
        ('studentapp', '0002_alter_student_student_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonRecommendation',
            fields=[
                ('lesson_rec_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recommendation_date', models.DateTimeField(auto_now_add=True)),
                ('recommendation_details', models.TextField()),
                ('applied_target_type', models.CharField(blank=True, choices=[('group', 'Group'), ('student', 'Student')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('dismiss', 'Dismissed')], default='pending', max_length=10)),
                ('applied_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_recommendations', to='groupapp.group')),
                ('applied_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_recommendations', to='studentapp.student')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_recommendations', to='assignmentapp.assignment')),
            ],
            options={
                'db_table': 'lesson_recommendations',
                'ordering': ['-recommendation_date'],
                'indexes': [models.Index(fields=['assignment', 'status'], name='lesson_reco_assignm_975b8b_idx')],
            },
        ),
    ]
