# Generated by Django 5.0.6 on 2026-07-07 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groupapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=150)),
                ('student_image', models.URLField(blank=True, max_length=255, null=True)),
                ('student_roll', models.CharField(max_length=50)),
                ('student_grade', models.CharField(max_length=20)),
                ('risk_status', models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('advance', 'Advance'), ('developing', 'Developing')], default='on_track', max_length=20)),
                ('reading_level', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=150, null=True)),
                ('parent_email', models.EmailField(blank=True, max_length=150, null=True)),
                ('avg_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('attendance_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_students', to='groupapp.group')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['student_name'],
                'indexes': [models.Index(fields=['teacher', 'risk_status'], name='students_teacher_2c8be4_idx'), models.Index(fields=['teacher', 'student_name'], name='students_teacher_88b12c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('teacher', 'student_roll'), name='uq_teacher_roll'),
        ),
    ]
