# Generated by Django 5.2.13 on 2026-07-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_image',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/'),
        ),
    ]
