# Generated by Django 5.2.13 on 2026-07-09 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignmentapp', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PacingRecommendation',
            fields=[
                ('pacing_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=200)),
                ('curriculum_adjustment', models.TextField()),
                ('standards_coverage_checklist', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacing_recommendations', to='assignmentapp.assignment')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacing_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pacing_recommendations',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['teacher', 'topic'], name='pacing_reco_teacher_f67c5a_idx')],
            },
        ),
    ]
