# Generated by Django 5.0.6 on 2026-07-07 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('activity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('assignment_created', 'Assignment Created'), ('assignment_submitted', 'Assignment Submitted'), ('mail_sent', 'Mail Sent'), ('group_generated', 'Group Generated'), ('intervention_created', 'Intervention Created'), ('observation_added', 'Observation Added'), ('attendance_marked', 'Attendance Marked'), ('feedback_added', 'Feedback Added'), ('message_sent', 'Message Sent')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('reference_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher', '-created_at'], name='activity_lo_teacher_727fe4_idx')],
            },
        ),
    ]
